// Ques: 108. Convert Sorted Array to Binary Search Tree
// https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/

var sortedArrayToBST = function(nums) {
    // Call the function recursively...
	return ConvertToBST(nums, 0, nums.length - 1);
}
// Create a function which will convert any particular range of given nums array...
// & return its corresponding BST root node....
var ConvertToBST = function(nums, beg, end) {
    // If beg > end, return NULL, as we receive a wrong range...
	if (beg > end)
		return null;
    // set the middle node...
	const mid = Math.ceil((beg + end) / 2);
    // Initialise root node with value same as nums[mid]...
	const rootNode = new TreeNode(nums[mid]);
    // Assign left subtrees as the same function called on left subranges...
	rootNode.left = ConvertToBST(nums, beg, mid - 1);
    // Assign right subtrees as the same function called on right subranges...
	rootNode.right = ConvertToBST(nums, mid + 1, end);
    // Return the root node...
	return rootNode;
};
